### ISSUE TITLE
any chance to make assetmanager as a build tool 

### ISSUE THREAD

**Issue by guileen** [mape/connect-assetmanager#10]
currently it is runtime middleware, but I'd like to make assetmanager use as a build tool, and then there is no runtime cost.

**Comment by mape** [comment]
The way it functions now is that it caches buffers. Early tests showed that the network will be saturated far faster then the cpu becomes an issue.

17005 req/sec on a 170byte asset and pushes around 0.7Gbit on for example jquery.js

I don't feel performance is an issue but if you want to use parts of the code to create a build tool you are more then welcome.

**Comment by eirikurn** [comment]
mape, there's more to it. I would say there are two related issues.

In my project, when I restart the server, either while developing or when updating production, the server always recompiles all assets. This is beginning to take quite a few seconds. During these seconds, the server responds with garbage. This could either be improved by using assetmanager as a build tool, or improving it so it caches and temporarily serves previous assets on the file system.

The second use case is for larger sites where you start to migrate to more servers and more domains and want your assets to be served as optimally as possible, f.ex. from a seperate cookie-less domain directly from nginx. Or even from a CDN where your only choice is to use static files.

**Comment by ivolo** [comment]
Also, if used as a build tool (or one that can write the result somewhere on disk), you can then use it in conjunction with nginx which can then gzip the script / css files. I think I read that there is no recommended implementation of gzip into express.

**Comment by eirikurn** [comment]
Well, there is a built in support for zlib coming in latest node. But
building for external hosting is still very useful, f.ex. for CDN.

On 14.10.2011, at 02:29, Ilya Volodarsky
reply@reply.github.com
wrote:
