### ISSUE TITLE
Question: How to have md5 appended to asset urls?

### ISSUE THREAD

**Issue by lukegalea** [mape/connect-assetmanager#12]
@mape: I'd like to append the md5 to the filename to ensure "cache busting". Is there an easy way to do that using assetmanager? I imagine that an asset_url helper in express could easily generate the md5, but the bundled files are somewhat ephemeral given they don't necessarily exist on disk.. it should probably be implemented via a call to assetmanager to request the md5.

Thoughts?

**Comment by mape** [comment]
This should now be possible (after https://github.com/mape/connect-assetmanager/commit/63849ddd66011d6ad91833310b57beb9d584fe72).
