### ISSUE TITLE
Asset Manager has a bunch of leaked globals

### ISSUE THREAD

**Issue by dylang** [mape/connect-assetmanager#20]
Hi Mape - I just used [Gleak](https://github.com/aheckmann/gleak) and found that AssettManager has a bunch of accidental global variables.  I think the use of `this` outside the closure is causing it.

```
found global leak: tls
found global leak: cacheTimestamps
found global leak: cacheHashes
found global leak: generateCache
found global leak: manipulate
found global leak: getFile
```

**Comment by mape** [comment]
Thanks for pointing that out, I'll take a peek at what is causing it.

**Comment by dsiu** [comment]
any progress on this?  'ret' on global is also leak.  it holds the content of the stitched js files.

**Comment by dsiu** [comment]
upon some peeking, I found the leak is in `deps/jsmin.js:364`

``` javascript
  jsmin.oldSize = input.length;
  ret = m(input);                        // <---- culprit here
  jsmin.newSize = ret.length;

  return comment + ret;
```

I will submit a patch

**Comment by dylang** [comment]
I no longer require this change.
