### ISSUE TITLE
user agent can be null, causing an error

### ISSUE THREAD

**Issue by dylang** [mape/connect-assetmanager#21]
This can be null (from `assettmanager.js`):

```
            var userAgent = req.headers['user-agent'];
```

which results in an error a few lines down:

```
                    if (!found && userAgent.match(new RegExp(match, 'i'))) {
                                            ^          
                    TypeError: Cannot call method 'match' of undefined
```

I'm guessing some user with super privacy is hiding his user agent, or some bot.

**Comment by mape** [comment]
This should have been fixed by commit 8e1be61a9075f54a579f8d489ddede37032ae12b
