### ISSUE TITLE
express example

### ISSUE THREAD

**Issue by ghost** [mape/connect-assetmanager#42]
Any chance we could get an express example in the readme? See a question on this here: http://stackoverflow.com/questions/11938434/express-and-connect-assetmanager

**Comment by ghost** [comment]
Maybe express isn't the issue so much as including a jade or ejs view snippet in the example so people would understand what the example regex is matching.

**Comment by laurentdebricon** [comment]
I agree, the readme is confusing, what's the point of allowing multi-route if it point to the same file ...
